"""
-------------------------------------------------------
THIS FILE IS AUTO-GENERATED.
DO NOT EDIT MANUALLY.
Changes may be overwritten during the next pipeline run.
-------------------------------------------------------

Changelog Generator.
Generates an automated markdown changelog based on metadata indexes.
"""
import os
import json
from datetime import datetime, timezone
from scripts.lib.logger import setup_logger

logger = setup_logger("changelog_generator")

class ChangelogGenerator:
    def __init__(self):
        self.metadata_dir = os.path.join("data", "metadata")

    def generate(self, release_version: str) -> str:
        logger.info(f"Generating changelog for release {release_version}")
        
        index_path = os.path.join(self.metadata_dir, "entity_index.json")
        if not os.path.exists(index_path):
            return "No data available."

        try:
            with open(index_path, "r", encoding="utf-8") as f:
                entities = json.load(f)
        except Exception as e:
            logger.error(f"Failed to load entity index: {e}")
            return f"Error generating changelog: {e}"

        total_entities = len(entities)
        
        lines = [
            f"# Release {release_version}",
            f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            "",
            f"## Data Overview",
            f"- Total entities indexed: **{total_entities}**",
            "",
            "## Highlights",
            "*(Automated summaries of new additions will be populated here)*",
            "",
            "---\n*Generated by AI Intelligence Archive Phase 5*"
        ]
        
        return "\n".join(lines)
