import os
from typing import Dict, Any
from scripts.lib.base_generator import BaseGenerator

class SelfDocumentation(BaseGenerator):
    def __init__(self):
        super().__init__("self_documentation", phase=7)
        
    def generate(self) -> Dict[str, Any]:
        """
        Auto-generates docs/system_overview.md and docs/generated_architecture.md
        without mutating manual docs.
        """
        os.makedirs("docs", exist_ok=True)
        
        system_overview = (
            "# System Overview\n\n"
            "This document is automatically generated by Phase 7 Self-Documentation.\n\n"
            "## Data Directories\n"
            "- **data/models**: Canonical models\n"
            "- **data/datasets**: Canonical datasets\n"
            "- **data/tools**: Canonical tools\n"
            "- **data/metadata**: Generated indices and knowledge graphs\n"
            "\n"
            "## Architecture Phases\n"
            "1. Core Framework\n2. Live Intelligence Ingestion\n3. Knowledge Expansion\n4. Intelligence Processing\n"
            "5. Repository Stabilization\n6. Ecosystem Intelligence\n7. Governance & Self-Maintenance\n"
        )
        
        architecture = (
            "# Generated Architecture\n\n"
            "This repository operates on a 100% database-free, deterministic pipeline.\n"
            "All writes are atomic `.tmp` replacements ensuring zero-downtime consistency.\n"
        )
        
        self.save_markdown("docs/system_overview.md", system_overview)
        self.save_markdown("docs/generated_architecture.md", architecture)
        
        return {"records_processed": 2}

    def run(self):
        self.generate()
